on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: arctonydemo.azurecr.io
        username: ${{ secrets.acr_arctonydemo_username }}
        password: ${{ secrets.acr_arctonydemo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t arctonydemo.azurecr.io/akstonydemo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push arctonydemo.azurecr.io/akstonydemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akstonydemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-tony-demoaf35 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-tony-demoaf35`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-tony-demoaf35
        container-registry-url: arctonydemo.azurecr.io
        container-registry-username: ${{ secrets.acr_arctonydemo_username }}
        container-registry-password: ${{ secrets.acr_arctonydemo_password }}
        secret-name: akstonydemodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-tony-demoaf35
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          arctonydemo.azurecr.io/akstonydemo:${{ github.sha }}
        imagepullsecrets: |
          akstonydemodockerauth
